# Generated by Django 6.0.5 on 2026-06-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyinfo',
            name='is_monitoring_active',
            field=models.BooleanField(default=True),
        ),
    ]
