# Generated by Django 6.0.5 on 2026-06-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_safetyinfo_is_monitoring_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyinfo',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
