# Generated by Django 6.0.5 on 2026-07-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_safetyinfo_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustedcontact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contacts/'),
        ),
    ]
