# Generated by Django 6.0.5 on 2026-07-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_trustedcontact_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms_credits',
            field=models.IntegerField(default=20),
        ),
    ]
