# Generated by Django 4.2.30 on 2026-07-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_sms_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trustedcontact',
            name='email',
        ),
    ]
