# Generated by Django 4.2.30 on 2026-07-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_trustedcontact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='caregiver_name',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='caregiver_phone',
        ),
    ]
