# Generated by Django 4.2.30 on 2026-07-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_pet_caregiver_name_remove_pet_caregiver_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=20),
        ),
    ]
