# Generated by Django 4.2.30 on 2026-07-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_subscription_expires_at_user_subscription_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sms_credits',
            field=models.IntegerField(default=0),
        ),
    ]
