# Generated by Django 4.2.30 on 2026-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('checked_in', 'Checked In'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
