# Generated by Django 6.0.5 on 2026-06-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringlog',
            name='sleep_mode',
            field=models.BooleanField(default=False),
        ),
    ]
