# Generated by Django 4.2.30 on 2026-07-24 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0002_alter_monitoringlog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('SIGNUP', 'Signup'), ('SIGNIN', 'Sign In'), ('LOGOUT', 'Logout'), ('LOGOUT_FAILED', 'Logout Failed'), ('CHECK_IN', 'Check In'), ('MONITORING_ACTIVATED', 'Monitoring Activated'), ('MONITORING_DEACTIVATED', 'Monitoring Deactivated'), ('OVERDUE_DETECTED', 'Overdue Detected'), ('SMS_SENT', 'SMS Sent'), ('SMS_FAILED', 'SMS Failed'), ('SLEEP_MODE_ON', 'Sleep Mode On'), ('SLEEP_MODE_OFF', 'Sleep Mode Off'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('PROFILE_UPDATED', 'Profile Updated'), ('ACCOUNT_DELETED', 'Account Deleted')], max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitoring_activity_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
